mqtt:
  enabled: false

audio:
  enabled: true

logger:
  default: error

detect:
  enabled: false

motion:
  enabled: false


ffmpeg:
  hwaccel_args: preset-rpi-64-h264

go2rtc:
  log:
    level: info
  streams:
    roadside:
      - rtsp://{FRIGATE_CAM_USERNAME}:{FRIGATE_CAM_PASSWORD}@192.168.18.102:554/stream1
      - ffmpeg:roadside#audio=aac

    roadside_sub:
      - rtsp://{FRIGATE_CAM_USERNAME}:{FRIGATE_CAM_PASSWORD}@192.168.18.102:554/stream2

    stairs:
      - rtsp://{FRIGATE_CAM_USERNAME}:{FRIGATE_CAM_PASSWORD}@192.168.18.101:554/stream1
      - ffmpeg:stairs#audio=aac

    stairs_sub:
      - rtsp://{FRIGATE_CAM_USERNAME}:{FRIGATE_CAM_PASSWORD}@192.168.18.101:554/stream2

  webrtc:
    candidates:
      - localhost:8555
      - stun:8555

cameras:
  roadside:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://127.0.0.1:8554/roadside
          input_args: preset-rtsp-restream
          roles:
            - record
            - audio
        - path: rtsp://127.0.0.1:8554/roadside_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    live:
      streams:
        Roadside: roadside

    zones:
      Main_Gate:
        coordinates: 0.153,0.237,0.219,0.197,0.522,0.999,0.203,1,0.081,0.292
        loitering_time: 0
        objects: person
    review: {}
    motion:
      threshold: 50
      contour_area: 10
      improve_contrast: true
  stairs:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://127.0.0.1:8554/stairs
          input_args: preset-rtsp-restream
          roles:
            - record
            - audio
        - path: rtsp://127.0.0.1:8554/stairs_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    live:
      streams:
        Stairs: stairs

    zones:
      Stairs:
        coordinates: 1,0,1,0.365,0.5,0.368,0.442,0.413,0.674,1,0,1,0,0
        loitering_time: 0
        objects: person
    review: {}
    motion:
      threshold: 50
      contour_area: 10
      improve_contrast: true

review:
  alerts:
    enabled: false
  detections:
    enabled: true

record:
  enabled: true
  retain:
    days: 10
    mode: all
  alerts:
    retain:
      days: 0
      mode: active_objects
  detections:
    retain:
      days: 0
      mode: active_objects

camera_groups:
  Home:
    order: 1
    icon: LuBuilding
    cameras:
      - roadside
      - stairs